name: VotingSample
ingress:
  - name: ingress
    bindings:
      - port: 8080
    rules:
      - path: /vote
        service: vote
      - path: /results
        service: results      
services:
- name: vote
  project: vote/vote.csproj
- name: redis
  image: redis
  bindings:
    - port: 6379
      connectionString: ${host}:${port}
- name: worker
  project: worker/worker.csproj
- name: postgres
  image:  postgres
  env:
  - name: TEST_RANDOM
    value: ${rand:guid}
  - name: POSTGRES_PASSWORD
    value: ${secret:PostresPassword}
  secrets:
  - name: PostresPassword
    source: TyeVault
    sourceKind: KeyVault
  bindings:
  - port: 5432
    connectionString: Server=${host};Port=${port};User Id=postgres;Password=${env:PostresPassword};
- name: results
  project: results/results.csproj
